name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Setup Vulkan
        run: |
          sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          sudo apt install xorg-dev
          sudo apt install vulkan-tools
          sudo apt install libvulkan-dev
          sudo apt install vulkan-validationlayers-dev spirv-tools
        
      - name: Build sample app
        run: bazelisk build //src:main --verbose_failures

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest

    steps:   
      - uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Build sample app
        run: bazelisk build //src:main --verbose_failures
        
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:   
      - uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Build sample app
        run: bazelisk build //src:main --verbose_failures
