name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run_sample_app:
    name: Run sample app
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Setup Vulkan
        run: |
          sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          sudo apt install xorg-dev
          sudo apt install vulkan-tools
          sudo apt install libvulkan-dev
          sudo apt install vulkan-validationlayers-dev spirv-tools
        
      - name: Run sample app
        run: |
          echo Running Vulkan sample app
          bazelisk run //src:main
